<?php

namespace App\Commands;

use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;
use Config\App;

class LangScaffold extends BaseCommand
{
    protected $group = 'Language';
    protected $name = 'lang:scaffold';
    protected $description = 'Generate language file scaffolds for LandingPage across configured locales';
    protected $usage = 'lang:scaffold [options]';
    protected $arguments = [];
    protected $options = [
        'languages' => 'Comma-separated list of locales to scaffold (default: from Config\App)',
        'faq-count' => 'Number of FAQ questions to scaffold (default: 4)',
        'force' => 'Overwrite existing files',
    ];

    public function run(array $params)
    {
        $appConfig = config(App::class);
        $defaultLocales = $appConfig->supportedLocales ?? ['es', 'en'];

        // Handle both formats: --languages=value and --languages value
        $languagesOpt = $params['languages'] ?? CLI::getOption('languages');
        $languages = $languagesOpt
            ? array_map('trim', explode(',', $languagesOpt))
            : $defaultLocales;

        // Handle both formats for numeric options
        $faqCountOpt = $params['faq-count'] ?? $params['faq_count'] ?? CLI::getOption('faq-count');
        $faqCount = (int) ($faqCountOpt ?? 4);

        $force = isset($params['force']) || CLI::getOption('force') !== null;
        $languagePath = APPPATH . 'Language';

        CLI::write(sprintf('Scaffolding language files for: %s', implode(', ', $languages)), 'cyan');
        CLI::write(sprintf('FAQ questions per locale: %d', $faqCount), 'cyan');
        CLI::newLine();

        $created = [];
        $skipped = [];
        $overwritten = [];

        foreach ($languages as $locale) {
            $localeDir = $languagePath . DIRECTORY_SEPARATOR . $locale;
            $filePath = $localeDir . DIRECTORY_SEPARATOR . 'LandingPage.php';

            if (!is_dir($localeDir)) {
                mkdir($localeDir, 0755, true);
            }

            $fileExists = file_exists($filePath);

            if ($fileExists && !$force) {
                $skipped[] = $locale;
                CLI::write(sprintf('⊘ %s: File exists (use --force to overwrite)', $locale), 'yellow');
                continue;
            }

            $content = $this->generateContent($locale, $faqCount);
            file_put_contents($filePath, $content);

            if ($fileExists && $force) {
                $overwritten[] = $locale;
                CLI::write(sprintf('⟳ %s: Overwritten', $locale), 'yellow');
            } else {
                $created[] = $locale;
                CLI::write(sprintf('✓ %s: Created', $locale), 'green');
            }
        }

        CLI::newLine();
        CLI::write(sprintf('Created: %d', count($created)), 'green');
        if (!empty($created)) {
            CLI::write('  ' . implode(', ', $created), 'green');
        }

        if (!empty($overwritten)) {
            CLI::write(sprintf('Overwritten: %d', count($overwritten)), 'yellow');
            CLI::write('  ' . implode(', ', $overwritten), 'yellow');
        }

        if (!empty($skipped)) {
            CLI::write(sprintf('Skipped: %d', count($skipped)), 'yellow');
            CLI::write('  ' . implode(', ', $skipped), 'yellow');
        }

        CLI::newLine();
        CLI::write('✓ Language scaffold generation complete.', 'green');
    }

    private function generateContent(string $locale, int $faqCount): string
    {
        $faqQuestions = $this->generateFaqQuestions($faqCount);

        $php = "<?php\n";
        $php .= "// Generated by: php spark lang:scaffold\n";
        $php .= "// Locale: {$locale}\n";
        $php .= "// Generated at: " . date('Y-m-d H:i:s') . "\n";
        $php .= "// TODO: Fill in all empty string values with content in this language\n\n";
        $php .= "return [\n";

        $php .= $this->generateMetaSection();
        $php .= $this->generateHeaderSection();
        $php .= $this->generateHeroSection();
        $php .= $this->generateOptionsSection();
        $php .= $this->generateFaqSection($faqQuestions);
        $php .= $this->generateFooterSection();

        $php .= "];\n";

        return $php;
    }

    private function generateMetaSection(): string
    {
        return <<<'PHP'
    // META TAGS
    'meta' => [
        'title' => '',
        'description' => '',
        'keywords' => '',
        'og_title' => '',
        'og_description' => '',
        'twitter_title' => '',
        'twitter_description' => ''
    ],

PHP;
    }

    private function generateHeaderSection(): string
    {
        return <<<'PHP'
    // HEADER
    'header' => [
        'logo_alt' => '',
        'tagline' => ''
    ],

PHP;
    }

    private function generateHeroSection(): string
    {
        return <<<'PHP'
    // HERO SECTION
    'hero' => [
        'title' => '',
        'description' => '',
        'newsletter_instruction' => '',
        'email_placeholder' => '',
        'subscribe_btn' => '',
        'portfolio_title' => '',
        'visibility_title' => '',
        'search_title' => ''
    ],

PHP;
    }

    private function generateOptionsSection(): string
    {
        return <<<'PHP'
    // OPTIONS SECTION
    'options' => [
        'portfolio' => [
            'title' => '',
            'description' => ''
        ],
        'search' => [
            'title' => '',
            'description' => ''
        ]
    ],

PHP;
    }

    private function generateFaqSection(string $faqQuestions): string
    {
        return <<<PHP
    // FAQ SECTION
    'faq' => [
        'title' => '',
        'description' => '',
        'questions' => [
{$faqQuestions}        ]
    ],

PHP;
    }

    private function generateFaqQuestions(int $count): string
    {
        $questions = [];

        for ($i = 0; $i < $count; $i++) {
            $questions[] = <<<'PHP'
            [
                'question' => '',
                'answer' => [
                    'intro' => '',
                    'benefits' => [],
                    'outro' => '',
                ],
            ],
PHP;
        }

        return implode("\n", $questions) . "\n";
    }

    private function generateFooterSection(): string
    {
        return <<<'PHP'
    // FOOTER
    'footer' => [
        'newsletter_text' => '',
        'email_placeholder' => '',
        'subscribe_btn' => '',
        'copyright' => ''
    ]
PHP;
    }
}
